###
POST http://127.0.0.1:3000/gerar-gabarito
Content-Type: application/json
// é bom usar o mesmo nome pra poder sempre fazer o overwriting

{
  "totalQuestions": 20,
  "altsPerQuestion": 5,
  "testID": "A-2026"
}